/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KwcInputGroup {
        /**
          * @default null
         */
        "value": string;
    }
}
declare global {
    interface HTMLKwcInputGroupElement extends Components.KwcInputGroup, HTMLStencilElement {
    }
    var HTMLKwcInputGroupElement: {
        prototype: HTMLKwcInputGroupElement;
        new (): HTMLKwcInputGroupElement;
    };
    interface HTMLElementTagNameMap {
        "kwc-input-group": HTMLKwcInputGroupElement;
    }
}
declare namespace LocalJSX {
    interface KwcInputGroup {
        /**
          * @default null
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "kwc-input-group": KwcInputGroup;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kwc-input-group": LocalJSX.KwcInputGroup & JSXBase.HTMLAttributes<HTMLKwcInputGroupElement>;
        }
    }
}
